apiVersion: v1

kind: Service

metadata:
  name: cloudmart-service

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

spec:

  type: LoadBalancer

  loadBalancerSourceRanges:
    - 0.0.0.0/0

  selector:
    app: cloudmart-platform

  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP